// <auto-generated />
namespace IMS_New.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeInterview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeInterview));
        
        string IMigrationMetadata.Id
        {
            get { return "201904280745277_changeInterview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
